services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /application
    volumes:
      - ./:/application
    networks:
      - financial-network
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/application
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - financial-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - financial-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

networks:
  financial-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
